Name = input("Enter a Name: ")
Age = input("Enter a Age: ")
City = input("Enter a City: ")
DOB = input("Enter a DOB: ")
College = input("Enter a College: ")
Blood_Group = input("Enter a Blood Group: ")

print("\n------STUDENT ID CARD------")
print("Name:", Name)
print("Age:", Age)
print("City:", City)
print("DOB:", DOB)
print("College:", College)
print("Blood Group:", Blood_Group)