Name = input("Name: ")
Age = input("Age: ")
City = input("City: ")
DOB = input("DOB: ")
College = input("College: ")
Blood_Group = input("Blood Group: ")

print("\n------STUDENT ID CARD------")
print("Name:", Name)
print("Age:", Age)
print("City:", City)
print("DOB:", DOB)
print("College:", College)
print("Blood Group:", Blood_Group)